// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Sqlite;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microsoft.EntityFrameworkCore.Sqlite.Migrations
{
    [DbContext(typeof(NodaTimeContext))]
    partial class NodaTimeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder.Entity("Microsoft.EntityFrameworkCore.Sqlite.NodaTimeTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NodaTimeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instant = "2020-10-10 23:42:16.321",
                            LocalDate = "2020-10-10",
                            LocalDateTime = "2020-10-10 23:42:16.321",
                            LocalTime = "23:42:16.321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
